language: python
python:
- '3.6'
env: "-DJANGO=3.0.3"
install:
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py runserver
deploy:
  provider: heroku
  api_key:
    secure: k0EgSWVNoeaRjvYCJRBKmBwHFe4tSl4P6z5HwKthAl8rBbbJdSydELw20tyyZmT1hfOIwPm6MBcNod5D5KdAx7O3rSJ7Gclj9rV6j2ttntbcaF800oCPPUpU2kXw2JkS6YLWZyL+bTPWMyhOTzI6u4HOWSEXKXGdW7YvZIXMiQ0YL8xb3YZDla5SDpkHLfvxU8UkspL+0LMaoQATevHLKjIYLd7Gis1hC+m6HUIHx72Ys943uWjAJLgMmVVyywyLCyn/sv4ZPad/TAa/WIqTbrVgAtjj/g7S3kAMm5d1WDL5qRyY3+fkrNQu4aZsOB7dbAP/J58u3b11i6qU+ESfJyG1jh4uVyP2OGK4sWnItBdc62ZrwE3VRccfz+NX2kZGVxTgQjc/jXjDRLbUwbRXkGOL1kPIBUbYTfje7keGSdkXGZSvteWtzT77Dsr1sXP/kRKieCw+Q8XN+kbYTZu9vxigtVMCnrmXHCEB8IVujwAy3K1E+M2zA6kgWxqKx54tfNgXlmrsEdCK3Bv/KLIT0ewxCEko0e7vXZTWHvO4n263u6zM5ols+5+AitX7M37zPxSDLzKsQrHTha77v1M/Hd7X65P+k/b+sryK6Sani4pDzq/MbT72hmSw3BQlf94Pa4HDO4Z4jlaTfGEw1Hl0eFxmV8rnYdFQUruw4UkV5jM=
  app: agilagic
  on:
    repo: vdblm/agilagic
