# Generated by Django 3.0.3 on 2020-02-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '0001_initial'),
        ('contract_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_seller', to='user_authentication.WebsiteSeller'),
        ),
    ]
