# Generated by Django 3.0.3 on 2020-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('C', 'Charge Account'), ('B', 'Buy Product'), ('D', 'Divide')], default=1, max_length=2)),
                ('amount', models.BigIntegerField(default=0)),
            ],
        ),
    ]
