# Generated by Django 3.0.3 on 2020-02-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('available_number', models.IntegerField()),
                ('description', models.TextField(default=1)),
                ('status', models.CharField(choices=[('P', 'در حال انتظار'), ('S', 'تایید شده'), ('U', 'رد شده'), ('H', 'پنهان')], max_length=2)),
                ('price', models.BigIntegerField(default=0)),
                ('img', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
