# Generated by Django 3.0.3 on 2020-02-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '0001_initial'),
        ('products_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbasket',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.WebsiteCustomer'),
        ),
        migrations.AddField(
            model_name='productbasket',
            name='products',
            field=models.ManyToManyField(to='products_transaction.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='user_authentication.WebsiteSeller'),
        ),
    ]
